# Postgres and pgAdmin4 stack for development

version: "3.1"

services:
  server:
    image: node-memories
    depends_on:
      - db
    restart: always
    ports:
      - "3333:3333"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
